######################################################################
# Automatically generated by qmake (2.01a) Pzt 12. Nis 18:46:42 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += static
CONFIG += release
#CONFIG += debug
#CONFIG += console

#LIBS += -lgdi32

# Input
HEADERS += figureframe.h mmcutil.h
SOURCES += main.cpp

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
