######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 17 15:58:00 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mresult.h mmcresult.h
SOURCES += main.cpp
