######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 18 07:27:24 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += figureframe.h lineedit.h mmcexam.h textedit.h
SOURCES += main.cpp
